### ISSUE TITLE
Which tag corresponds to the latest release?

### ISSUE THREAD

**Issue by Dantheman720** [jboss-developer/jboss-jdg-quickstarts#102]
We are updating the quickstart versions on developers.redhat.com, and wanted to make sure that we have the most current GA (or approved - we suspected 6.5.1.CR1) release available so that the quickstarts are in sync and we aren't leading people to unsupported versions on our site.

**Comment by dmstahl** [comment]
Hi.  Yes, 6.5.1.CR1 is the 6.5.1 GA release.   It has also been retagged as JDG_6.5.1.GA.

**Comment by Dantheman720** [comment]
Awesome!  Thanks
