### ISSUE TITLE
There is no contributing guide and links to a contributing guide 404

### ISSUE THREAD

**Issue by LightGuard** [jboss-developer/jboss-jdg-quickstarts#68]
There should be a contributing guide in the root of the repo, and anything that links to said contributing guide should be relative.

**Comment by slaskawi** [comment]
Hey @LightGuard @sgilda @paulrobinson !

Is there anything which needs to be added to the quickstarts? If not - may I close it?

Thanks
Sebastian

**Comment by paulrobinson** [comment]
@LightGuard can you handle this query?

**Comment by LightGuard** [comment]
I'll go back and look, I don't recall anything else needing to be done, but
I'll double check.

On Mon, Jul 6, 2015 at 2:42 AM, Paul Robinson <notifications@github.com>
wrote:

> @LightGuard <https://github.com/LightGuard> can you handle this query?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jboss-developer/jboss-jdg-quickstarts/issues/68#issuecomment-118776340>
> .
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by LightGuard** [comment]
Looks like that bit about the contributing guide and links to the contributing guide are all that need fixing.
